# Generated by Django 3.0 on 2021-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainStrategy', models.CharField(blank=True, default='Strategy', max_length=20)),
                ('dateStrategy', models.DateTimeField(auto_now_add=True)),
                ('questionsToAddStrategy', models.CharField(max_length=256)),
                ('questionType', models.CharField(blank=True, max_length=20, null=True)),
                ('OptionsStrategy', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsValueStrategy', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
