# Generated by Django 3.0 on 2021-07-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('D1', 'Email'), ('D2', 'Website'), ('D3', 'Skills'), ('D4', 'Customers'), ('D5', 'Competitors'), ('D6', 'Finance'), ('D7', 'Sales')], max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('questionsToAdd', models.CharField(max_length=256)),
                ('OptionsOne', models.CharField(max_length=120)),
                ('OptionsOneValue', models.IntegerField()),
                ('OptionsTwo', models.CharField(max_length=120)),
                ('OptionsTwoValue', models.IntegerField()),
                ('OptionsThree', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsThreeValue', models.IntegerField(blank=True, null=True)),
                ('OptionsFour', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsFourValue', models.IntegerField(blank=True, null=True)),
                ('OptionsFive', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsFiveValue', models.IntegerField(blank=True, null=True)),
                ('OptionsSix', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsSixValue', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
