# Generated by Django 3.0 on 2021-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0002_auto_20210718_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='Finance', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('priority', models.IntegerField()),
                ('questionsToAdd', models.CharField(max_length=256)),
                ('OptionsOne', models.CharField(max_length=120)),
                ('OptionsOneValue', models.IntegerField()),
                ('OptionsTwo', models.CharField(max_length=120)),
                ('OptionsTwoValue', models.IntegerField()),
                ('OptionsThree', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsThreeValue', models.IntegerField(blank=True, null=True)),
                ('OptionsFour', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsFourValue', models.IntegerField(blank=True, null=True)),
                ('OptionsFive', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsFiveValue', models.IntegerField(blank=True, null=True)),
                ('OptionsSix', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsSixValue', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
