# Generated by Django 3.0 on 2021-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0004_auto_20210719_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainStrategy', models.CharField(blank=True, default='Finance', max_length=20)),
                ('dateStrategy', models.DateField(auto_now_add=True)),
                ('priorityStrategy', models.IntegerField()),
                ('questionsToAddStrategy', models.CharField(max_length=256)),
                ('OptionsOneStrategy', models.CharField(max_length=120)),
                ('OptionsOneValueStrategy', models.IntegerField()),
                ('OptionsTwoStrategy', models.CharField(max_length=120)),
                ('OptionsTwoValueStrategy', models.IntegerField()),
                ('OptionsThreeStrategy', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsThreeValueStrategy', models.IntegerField(blank=True, null=True)),
                ('OptionsFourStrategy', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsFourValueStrategy', models.IntegerField(blank=True, null=True)),
                ('OptionsFiveStrategy', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsFiveValueStrategy', models.IntegerField(blank=True, null=True)),
                ('OptionsSixStrategy', models.CharField(blank=True, max_length=120, null=True)),
                ('OptionsSixValueStrategy', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
