# Generated by Django 3.0 on 2021-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0005_modelstrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstrategy',
            name='domainStrategy',
            field=models.CharField(blank=True, default='Strategy', max_length=20),
        ),
    ]
