# Generated by Django 3.0 on 2021-07-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0007_modelcompetitors_modelcustomers_modelmarketing_modelportfolio_modelsales_modelskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcompetitors',
            name='domain',
            field=models.CharField(blank=True, default='Competitors', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelcustomers',
            name='domain',
            field=models.CharField(blank=True, default='Customers', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelmarketing',
            name='domain',
            field=models.CharField(blank=True, default='Marketing', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelportfolio',
            name='domain',
            field=models.CharField(blank=True, default='Portfolio', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelsales',
            name='domain',
            field=models.CharField(blank=True, default='Sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelskills',
            name='domain',
            field=models.CharField(blank=True, default='Skills', max_length=20),
        ),
    ]
