# Generated by Django 3.0 on 2021-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0008_auto_20210720_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsform',
            name='ans_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionsform',
            name='questionType',
            field=models.CharField(choices=[('1', 'options'), ('2', 'Text')], default='None', max_length=20),
            preserve_default=False,
        ),
    ]
