# Generated by Django 3.0 on 2021-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0009_auto_20210723_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcompetitors',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelcompetitors',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelcustomers',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelcustomers',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelfinance',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelfinance',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelmarketing',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelmarketing',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelportfolio',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelportfolio',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelsales',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelsales',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelskills',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelskills',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelstrategy',
            name='questionType',
            field=models.CharField(blank=True, choices=[('1', 'options'), ('2', 'Text')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelstrategy',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelcompetitors',
            name='OptionsOne',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelcompetitors',
            name='OptionsOneValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelcompetitors',
            name='OptionsTwo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelcompetitors',
            name='OptionsTwoValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelcustomers',
            name='OptionsOne',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelcustomers',
            name='OptionsOneValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelcustomers',
            name='OptionsTwoValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelmarketing',
            name='OptionsOne',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelmarketing',
            name='OptionsOneValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelmarketing',
            name='OptionsTwo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelmarketing',
            name='OptionsTwoValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelmarketing',
            name='questionsToAdd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modelportfolio',
            name='OptionsOne',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelportfolio',
            name='OptionsOneValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelportfolio',
            name='OptionsTwo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelportfolio',
            name='OptionsTwoValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsales',
            name='OptionsOne',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelsales',
            name='OptionsOneValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsales',
            name='OptionsTwo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelsales',
            name='OptionsTwoValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelskills',
            name='OptionsOne',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelskills',
            name='OptionsOneValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelskills',
            name='OptionsTwo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelskills',
            name='OptionsTwoValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelstrategy',
            name='OptionsOneStrategy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelstrategy',
            name='OptionsOneValueStrategy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelstrategy',
            name='OptionsTwoStrategy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='modelstrategy',
            name='OptionsTwoValueStrategy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
