# Generated by Django 3.0 on 2021-08-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0011_auto_20210729_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcustomers',
            name='OptionsTwo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
