from django.urls import path, include
from .views import *

urlpatterns = [
    path('AdminLogin', AdminLogin, name="adminLogin"),
    path('adminRegistration/', adminRegistration, name="AdminRegistration"),
    path('adminHome', adminHome, name="adminHome"),
    path('addQuestions', addQuestions, name="addQuestions"),
    path('delete-ques/<int:id>', delete_ques, name="delete_ques"),
    path('updateQues/<int:id>', updateQues, name="updateQues"),
    path('questionsDashboard', questionsDashboard, name="questionsDashboard"),
    # path('viewFinance', viewFinance, name="viewFinance"),
    path('financeHome', financeHome, name="financeHome"),
    path('StrategyHome', StrategyHome, name="StrategyHome"),
    path('PortfolioHome', PortfolioHome, name='PortfolioHome'),
    path('SkillsHome', SkillsHome, name='SkillsHome'),
    path('CustomersHome', CustomersHome, name='CustomersHome'),
    path('CompetitorsHome', CompetitorsHome, name='CompetitorsHome'),
    path('SalesHome', SalesHome, name='SalesHome'),
    path('MarketingHome', MarketingHome, name='MarketingHome'),
    # DELET QUESTIONS LINK
    path('delete-ques-competi/<int:id>',
         delete_ques_competi, name="delete_ques_competi"),
    path('delete_ques_stra/<int:id>',
         delete_ques_stra, name="delete_ques_stra"),
    path('delete_ques_fin/<int:id>', delete_ques_fin, name='delete_ques_fin'),
    path('delete_ques_portfo/<int:id>',
         delete_ques_portfo, name='delete_ques_fin'),
    path('delete_ques_skills/<int:id>',
         delete_ques_skills, name='delete_ques_skills'),
    path('delete_ques_custom/<int:id>',
         delete_ques_custom, name='delete_ques_custom'),
    path('delete_ques_sales/<int:id>',
         delete_ques_sales, name='delete_ques_sales'),
    path('delete_ques_marketing/<int:id>',
         delete_ques_marketing, name='delete_ques_marketing'),
    # UPDATE Question Urls
    path('updatefin/<int:id>', updatefin, name="updatefin"),
    path('updatestra/<int:id>', updatestra, name='updatestra'),
    path('updateportfolio/<int:id>', updateportfolio, name='updateportfolio'),
    path('updatecustomers/<int:id>', updatecustomers, name='updatecustomers'),
    path('updatecompetitors/<int:id>',
         updatecompetitors, name='updatecompetitors'),
    path('updatesales/<int:id>', updatesales, name='updatesales'),
    path('updatemarketing/<int:id>', updatemarketing, name='updatemarketing'),
    path('updateskills/<int:id>', updateskills, name='updateskills'),
    path('scrap', scrap, name='scrap'),
]
